piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: latest@sha256:417532baa2801288147cd9ac9ae260751c1a7754f0b829725d09b72a770c111a

linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true

linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: latest@sha256:e8329b3e07c47ec73a7d9644535639fd80dbe5c27a7e03181b999ebe072a3a2e
