---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.ferretdb-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: ferretdb
          path: apps/ferretdb
          libraries: [cozy-lib]
        - name: ferretdb-rd
          path: system/ferretdb-rd
          install:
            namespace: cozy-system
            releaseName: ferretdb-rd
