---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.foundationdb-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.foundationdb-operator
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: foundationdb
          path: apps/foundationdb
          libraries: ["cozy-lib"]
        - name: foundationdb-rd
          path: system/foundationdb-rd
          install:
            namespace: cozy-system
            releaseName: foundationdb-rd
