---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.info-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: info
          path: extra/info
          libraries: ["cozy-lib"]
        - name: info-rd
          path: system/info-rd
          install:
            namespace: cozy-system
            releaseName: info-rd
