---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.mysql-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.mariadb-operator
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: mysql
          path: apps/mysql
          libraries: ["cozy-lib"]
        - name: mysql-rd
          path: system/mysql-rd
          install:
            namespace: cozy-system
            releaseName: mysql-rd
