---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.rabbitmq-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.rabbitmq-operator
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: rabbitmq
          path: apps/rabbitmq
          libraries: ["cozy-lib"]
        - name: rabbitmq-rd
          path: system/rabbitmq-rd
          install:
            namespace: cozy-system
            releaseName: rabbitmq-rd
