---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.redis-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: default
      dependsOn:
        - cozystack.networking
        - cozystack.redis-operator
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: redis
          path: apps/redis
          libraries: ["cozy-lib"]
        - name: redis-rd
          path: system/redis-rd
          install:
            namespace: cozy-system
            releaseName: redis-rd
