---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.virtualprivatecloud-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: kubevirt
      dependsOn:
        - cozystack.networking
        - cozystack.multus
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: virtualprivatecloud
          path: apps/vpc
          libraries: [cozy-lib]
        - name: virtualprivatecloud-rd
          path: system/virtualprivatecloud-rd
          install:
            namespace: cozy-system
            releaseName: virtualprivatecloud-rd
