---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.vm-disk-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
    - name: kubevirt
      dependsOn:
        - cozystack.networking
        - cozystack.kubevirt-cdi
      libraries:
        - name: cozy-lib
          path: library/cozy-lib
      components:
        - name: vm-disk
          path: apps/vm-disk
          libraries: ["cozy-lib"]
        - name: vm-disk-rd
          path: system/vm-disk-rd
          install:
            namespace: cozy-system
            releaseName: vm-disk-rd
