{{- $host := index .Values._cluster "root-host" }}
{{- $exposeServices := splitList "," ((index .Values._cluster "expose-services") | default "") }}
{{- $exposeIngress := (index .Values._cluster "expose-ingress") | default "tenant-root" }}

{{- if and (has "vm-exportproxy" $exposeServices) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: vm-exportproxy
  namespace: cozy-kubevirt
spec:
  ingressClassName: {{ $exposeIngress }}
  rules:
  - host: vm-exportproxy.{{ $host }}
    http:
      paths:
      - backend:
          service:
            name: vm-exportproxy
            port:
              number: 443
        path: /
        pathType: ImplementationSpecific
{{- end }}
